# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.adscripcion_edit:
        class: AppBundle\Form\AdscripcionEditType
        arguments: ['@security.token_storage']
        tags:
            - { name: form.type }
